
package com.betfair.publicapi.v5.bfexchangeservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BFExchangeService", targetNamespace = "http://www.betfair.com/publicapi/v5/BFExchangeService/", wsdlLocation = "https://api.betfair.com/exchange/v5/BFExchangeService.wsdl")
public class BFExchangeService_Service
    extends Service
{

    private final static URL BFEXCHANGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.betfair.publicapi.v5.bfexchangeservice.BFExchangeService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.betfair.publicapi.v5.bfexchangeservice.BFExchangeService_Service.class.getResource(".");
            url = new URL(baseUrl, "https://api.betfair.com/exchange/v5/BFExchangeService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://api.betfair.com/exchange/v5/BFExchangeService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BFEXCHANGESERVICE_WSDL_LOCATION = url;
    }

    public BFExchangeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BFExchangeService_Service() {
        super(BFEXCHANGESERVICE_WSDL_LOCATION, new QName("http://www.betfair.com/publicapi/v5/BFExchangeService/", "BFExchangeService"));
    }

    /**
     * 
     * @return
     *     returns BFExchangeService
     */
    @WebEndpoint(name = "BFExchangeService")
    public BFExchangeService getBFExchangeService() {
        return super.getPort(new QName("http://www.betfair.com/publicapi/v5/BFExchangeService/", "BFExchangeService"), BFExchangeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BFExchangeService
     */
    @WebEndpoint(name = "BFExchangeService")
    public BFExchangeService getBFExchangeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.betfair.com/publicapi/v5/BFExchangeService/", "BFExchangeService"), BFExchangeService.class, features);
    }

}
